#!/usr/bin/env bash

# Check if all required parameters are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "${username}@${ip}:~/"

# Check the exit status of scp command
if [ $? -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
fi

