#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend lb_frontend
    bind *:80
    mode http
    default_backend lb_backend

backend lb_backend
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Restart HAProxy
sudo service haproxy restart

