#!/usr/bin/env bash
# Configure nginx to listen on port 80

# Remove the default configuration file
rm /etc/nginx/sites-enabled/default

# Create a new configuration file for port 80
cat <<EOF > /etc/nginx/sites-available/port_80
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/port_80 /etc/nginx/sites-enabled/port_80

# Restart nginx to apply the changes
service nginx restart

