#!/usr/bin/env bash

# Ensure Nginx is installed
apt-get update
apt-get install -y nginx

# Modify Nginx configuration to listen on port 80
sed -i 's/\(listen\s\+\)[0-9]\+/\180/' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

