#!/usr/bin/env bash
# configure the SSH config file to our needs so that
# you can connect to a server without typing a password

Host example-server
    HostName 98.98.98.98
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no

